#!/bin/sh
exec uci set network.mesh_wan.mesh_no_rebroadcast='1'
exec uci set network.mesh_lan.mesh_no_rebroadcast='1'
exec uci commit
exec uci set wireless.ibss_radio0.disabled='0'
exec uci set wireless.mesh_radio0.disabled='0'
exec uci commit
