#!/usr/bin/lua

local site = require 'gluon.site_config'
local util = require 'gluon.util'

local uci = require('luci.model.uci').cursor()

local function fix_radio(radio, index, config)
  local hwmode = uci:get('wireless', radio, 'hwmode')
  local channel = tonumber(uci:get('wireless', radio, 'channel'))

  uci:set('wireless', radio, 'htmode', 'HT40')
  uci:set('wireless', radio, 'noscan', '1')

  if hwmode == '11g' then
    if channel > 11 then
      uci:set('wireless', radio, 'country', 'BO')
    else
      uci:set('wireless', radio, 'country', '00')
    end

    uci:set('wireless', radio, 'country_ie', '0')

    uci:set('wireless', radio, 'supported_rates', '6000 9000 12000 18000 24000 36000 48000 54000')
    uci:set('wireless', radio, 'basic_rate', '6000 9000 18000 36000 54000')
  end
end

util.iterate_radios(fix_radio)

uci:save('wireless')
uci:commit('wireless')

