#!/usr/bin/lua

local util = require 'gluon.util'

local uci = require('luci.model.uci').cursor()

--local function cmd(_command)
--  local f = io.popen(_command)
--  local l = f:read("*a")
--  f:close()
--  return l
--end

local function fix_radio(radio, index, config)
  local hwmode = uci:get('wireless', radio, 'hwmode')
  local channel = tonumber(uci:get('wireless', radio, 'channel'))

  local htmode = 'HT40+'

  --- band 2.4 GHz
  if hwmode == '11g' then
    uci:delete('wireless', radio, 'txpower')

    uci:set('wireless', radio, 'country', 'BO')
    uci:set('wireless', radio, 'country_ie', '0')

    uci:set('wireless', radio, 'supported_rates', '6000 9000 12000 18000 24000 36000 48000 54000')
    uci:set('wireless', radio, 'basic_rate', '6000 9000 18000 36000 54000')

    if channel > 7 then
      htmode = 'HT40-'
    end
  --- band 5 GHz
  elseif hwmode == '11a' then
    if channel > 39 then
      htmode = 'HT40-'
    end

    --- disable mesh / ibss for ac devices
    --if cmd('iwinfo ' .. radio .. ' info | grep -o 802.11nac') == '802.11nac' then
    --  htmode = 'VHT80'
    --  if uci:get('wireless', 'mesh_' .. radio) == 'wifi-iface' then
    --    uci:set('wireless', 'mesh_' .. radio, 'disabled', '1')
    --  elseif uci:get('wireless', 'ibss_' .. radio) == 'wifi-iface' then
    --    uci:set('wireless', 'ibss_' .. radio, 'disabled', '1')
    --  end
    --end
  else
    htmode = 'HT40'
  end

  if type(config.htmode) == string then
    htmode = config.htmode
  end

  uci:set('wireless', radio, 'htmode', htmode)
  uci:set('wireless', radio, 'noscan', '1')
end

util.iterate_radios(fix_radio)

uci:save('wireless')
uci:commit('wireless')

