#!/usr/bin/lua

local site = require 'gluon.site'
local uci = require("simple-uci").cursor()
local util = require 'gluon.util'

local step_size = site.ath9kblackout.stepsize()

local f = io.open('/usr/lib/micron.d/ath9kblackout', 'w')
f:write(string.format('*/%i * * * * /usr/sbin/ath9kblackout\n', step_size))
f:close()
